host: 0.0.0.0
port: 9091
log_level: debug

theme: auto

# default_redirection_url: https://authelia.mytest.local

authentication_backend:
  file:
    path: /config/users.yml

identity_validation:
  reset_password:
    jwt_secret: "129649059bdfbf81898f3234487711ad706275966e57fd3d8c3389fe92f092b0"  # use a strong key in real setup

access_control:
  default_policy: deny
  rules:
    - domain: "*.mytest.local"
      policy: one_factor

session:
  secret: 'insecure_session_secret'
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - domain: 'mytest.local'
      authelia_url: 'https://authelia.mytest.local'
      default_redirection_url: 'https://gitea.mytest.local'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5m'
      expiration: '1h'
      remember_me: '1d'

storage:
  local:
    path: /config/db.sqlite3



