server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: gitea
    static_configs:
      - targets:
          - localhost
        labels:
          job: gitea
          __path__: /data/gitea/log/*.log

  - job_name: authelia
    static_configs:
      - targets:
          - localhost
        labels:
          job: authelia
          __path__: /var/log/authelia/*.log
