version: "3"

services:
  gitea-db:
    image: mariadb:10
    container_name: gitea-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gitea_root
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea_pass
    volumes:
      - ./gitea/db:/var/lib/mysql
    networks:
      - gitea-net
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
    volumes:
      - ./gitea/data:/data
    networks:
      - gitea-net
  nginx:
    image: nginx
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"   
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - gitea
    networks:
      - gitea-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - gitea-net    
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    environment:
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=12345678901234567890123456789012
    ports:
      - "9091:9091"
    volumes:
      - ./authelia/config:/config
      - ./authelia/db:/var/lib/authelia
      - ./authelia/logs:/var/log/authelia
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - gitea-net    

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/wal:/wal
      - ./loki/index:/loki/index
      - ./loki/chunks:/loki/chunks
      - ./loki/compactor:/loki/compactor
      - ./loki/cache:/loki/index_cache
    networks:
      - gitea-net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log              # system logs (optional)
      - ./loki/promtail-config.yaml:/etc/promtail/promtail.yaml
      - ./gitea/data/gitea/log:/data/gitea/log:ro      # your gitea logs location on host
      - ./authelia/logs:/var/log/authelia  # your authelia logs location on host
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - gitea-net

networks:
  gitea-net:
